QUESTIONS = {
    "science": [
        {"q": "What is the powerhouse of the cell?", "a": "mitochondria"},
        {"q": "What is the chemical symbol for gold?", "a": "au"},
        {"q": "Which planet is known as the Red Planet?", "a": "mars"},
        {"q": "What is the speed of light approx?", "a": "300000 km/s"},
        {"q": "What gas do plants absorb from the atmosphere?", "a": "carbon dioxide"},
        {"q": "What is the boiling point of water in Celsius?", "a": "100"},
        {"q": "What is the hardest natural substance on Earth?", "a": "diamond"},
        {"q": "Which part of the plant conducts photosynthesis?", "a": "leaf"},
        {"q": "What is the study of living organisms called?", "a": "biology"},
        {"q": "What is the atomic number of Hydrogen?", "a": "1"},
        {"q": "Which organ pumps blood in the human body?", "a": "heart"},
        {"q": "What is the largest organ in the human body?", "a": "skin"},
        {"q": "What is the process of water turning into vapor?", "a": "evaporation"},
        {"q": "What force pulls objects toward the center of the Earth?", "a": "gravity"},
        {"q": "What is the common name for Sodium Chloride?", "a": "salt"},
        {"q": "Which gas is most abundant in Earth's atmosphere?", "a": "nitrogen"},
        {"q": "What is the center of an atom called?", "a": "nucleus"},
        {"q": "How many bones are in the adult human body?", "a": "206"},
        {"q": "What is the main component of natural gas?", "a": "methane"},
        {"q": "Which vitamin is produced when skin is exposed to sunlight?", "a": "vitamin d"},
        {"q": "What is the unit of electric current?", "a": "ampere"},
        {"q": "What type of rock is formed by cooled lava?", "a": "igneous"},
        {"q": "What is the nearest star to Earth?", "a": "sun"},
        {"q": "What is the largest mammal in the world?", "a": "blue whale"},
        {"q": "Which element has the symbol O?", "a": "oxygen"},
        {"q": "What is the study of stars and planets called?", "a": "astronomy"},
        {"q": "What is the pH level of pure water?", "a": "7"},
        {"q": "Which part of the brain controls balance?", "a": "cerebellum"},
        {"q": "What is the first element on the periodic table?", "a": "hydrogen"},
        {"q": "What is the name of the galaxy we live in?", "a": "milky way"}
    ],
    "math": [
        {"q": "What is 5 + 7?", "a": "12"},
        {"q": "What is the square root of 64?", "a": "8"},
        {"q": "How many sides does a hexagon have?", "a": "6"},
        {"q": "What is 15% of 200?", "a": "30"},
        {"q": "What is the value of Pi (to 2 decimal places)?", "a": "3.14"},
        {"q": "What is 12 x 12?", "a": "144"},
        {"q": "How many degrees are in a right angle?", "a": "90"},
        {"q": "What is the measurement of a straight angle?", "a": "180"},
        {"q": "What is 100 divided by 4?", "a": "25"},
        {"q": "What is the sum of angles in a triangle?", "a": "180"},
        {"q": "What is 7 squared?", "a": "49"},
        {"q": "How many centimeters are in a meter?", "a": "100"},
        {"q": "What is 2 to the power of 5?", "a": "32"},
        {"q": "What is the area of a square with side 4?", "a": "16"},
        {"q": "What is the perimeter of a rectangle 5x3?", "a": "16"},
        {"q": "What is half of 50?", "a": "25"},
        {"q": "What is the cube root of 27?", "a": "3"},
        {"q": "How many seconds are in an hour?", "a": "3600"},
        {"q": "What is 9 x 8?", "a": "72"},
        {"q": "What is 50 + 50?", "a": "100"},
        {"q": "What is the next number in the sequence: 2, 4, 6, 8, ...?", "a": "10"},
        {"q": "What is 1000 - 450?", "a": "550"},
        {"q": "How many faces does a cube have?", "a": "6"},
        {"q": "What is 1/4 as a decimal?", "a": "0.25"},
        {"q": "What is 3 squared plus 4 squared?", "a": "25"},
        {"q": "What is the value of 0 factorial?", "a": "1"},
        {"q": "What is 20 multiplied by 5?", "a": "100"},
        {"q": "How many years are in a decade?", "a": "10"},
        {"q": "What is the diameter of a circle with radius 5?", "a": "10"},
        {"q": "What is 81 divided by 9?", "a": "9"}
    ],
    "history": [
        {"q": "Who was the first President of the USA?", "a": "george washington"},
        {"q": "In which year did WWII end?", "a": "1945"},
        {"q": "Who discovered America in 1492?", "a": "christopher columbus"},
        {"q": "What was the name of the ship that sank in 1912?", "a": "titanic"},
        {"q": "Who was known as the Maid of Orleans?", "a": "joan of arc"},
        {"q": "Which empire built the Colosseum?", "a": "roman empire"},
        {"q": "Who was the first man to step on the moon?", "a": "neil armstrong"},
        {"q": "In which city was John F. Kennedy assassinated?", "a": "dallas"},
        {"q": "Who wrote the Declaration of Independence?", "a": "thomas jefferson"},
        {"q": "What was the ancient Egyptian system of writing called?", "a": "hieroglyphics"},
        {"q": "Which country did the Renaissance start in?", "a": "italy"},
        {"q": "Who was the first female Prime Minister of the UK?", "a": "margaret thatcher"},
        {"q": "In what year did the French Revolution begin?", "a": "1789"},
        {"q": "Who was the leader of the Soviet Union during WWII?", "a": "joseph stalin"},
        {"q": "What was the name of the first artificial satellite?", "a": "sputnik"},
        {"q": "Which queen ruled England for 63 years until 1901?", "a": "queen victoria"},
        {"q": "Who was the first Emperor of China?", "a": "qin shi huang"},
        {"q": "In what year did the Berlin Wall fall?", "a": "1989"},
        {"q": "Who founded the Mongol Empire?", "a": "genghis khan"},
        {"q": "What was the main cause of the Black Death?", "a": "bacteria"},
        {"q": "Who was the American Civil Rights leader who had a dream?", "a": "martin luther king jr"},
        {"q": "Which war was fought between the North and South USA?", "a": "civil war"},
        {"q": "Who was the primary author of the Communist Manifesto?", "a": "karl marx"},
        {"q": "Which civilization built the pyramids of Giza?", "a": "egyptians"},
        {"q": "Who was the Greek god of the sea?", "a": "poseidon"},
        {"q": "In which year did the Titanic sink?", "a": "1912"},
        {"q": "Who was the famous nurse during the Crimean War?", "a": "florence nightingale"},
        {"q": "Which country gifted the Statue of Liberty to the USA?", "a": "france"},
        {"q": "What was the code name for the atomic bomb project?", "a": "manhattan project"},
        {"q": "Who was the last Tsar of Russia?", "a": "nicholas ii"}
    ],
    "geography": [
        {"q": "What is the capital of France?", "a": "paris"},
        {"q": "Which is the largest continent?", "a": "asia"},
        {"q": "What is the longest river in the world?", "a": "nile"},
        {"q": "Which country has the largest population?", "a": "india"},
        {"q": "What is the smallest country in the world?", "a": "vatican city"},
        {"q": "Which ocean is the largest?", "a": "pacific"},
        {"q": "What is the capital of Japan?", "a": "tokyo"},
        {"q": "In which country is Mount Everest located?", "a": "nepal"},
        {"q": "What is the largest desert in the world?", "a": "sahara"},
        {"q": "Which river flows through London?", "a": "thames"},
        {"q": "What is the capital of Italy?", "a": "rome"},
        {"q": "Which country is also a continent?", "a": "australia"},
        {"q": "What is the highest mountain in Africa?", "a": "kilimanjaro"},
        {"q": "Which sea is located between Europe and Africa?", "a": "mediterranean"},
        {"q": "What is the capital of Canada?", "a": "ottawa"},
        {"q": "Which state is the largest in the USA?", "a": "alaska"},
        {"q": "What is the currency of Japan?", "a": "yen"},
        {"q": "How many continents are there?", "a": "7"},
        {"q": "Which country is famous for the Taj Mahal?", "a": "india"},
        {"q": "What is the capital of Germany?", "a": "berlin"},
        {"q": "Which line divides the Earth into North and South?", "a": "equator"},
        {"q": "What is the capital of Australia?", "a": "canberra"},
        {"q": "Which country is the largest by land area?", "a": "russia"},
        {"q": "What is the capital of Egypt?", "a": "cairo"},
        {"q": "Which mountain range is in South America?", "a": "andes"},
        {"q": "What is the deepest point in the ocean?", "a": "mariana trench"},
        {"q": "Which country is home to the Amazon Rainforest?", "a": "brazil"},
        {"q": "What is the capital of Brazil?", "a": "brasilia"},
        {"q": "Which city is known as the Big Apple?", "a": "new york"},
        {"q": "Which pole is located in the Arctic?", "a": "north pole"}
    ],
    "computer science": [
        {"q": "What does CPU stand for?", "a": "central processing unit"},
        {"q": "Who is known as the father of computers?", "a": "charles babbage"},
        {"q": "What does HTTP stand for?", "a": "hypertext transfer protocol"},
        {"q": "Which company developed Java?", "a": "sun microsystems"},
        {"q": "What is the binary representation of 2?", "a": "10"},
        {"q": "What does RAM stand for?", "a": "random access memory"},
        {"q": "Which logic gate returns true only if both inputs are true?", "a": "and"},
        {"q": "What is the main language used for web styling?", "a": "css"},
        {"q": "What does SQL stand for?", "a": "structured query language"},
        {"q": "Who co-founded Microsoft?", "a": "bill gates"},
        {"q": "What is the name of the first computer programmer?", "a": "ada lovelace"},
        {"q": "Which OS is known for its penguin mascot?", "a": "linux"},
        {"q": "What does HTML stand for?", "a": "hypertext markup language"},
        {"q": "What is a common name for a software error?", "a": "bug"},
        {"q": "Which part of the computer is the brain?", "a": "cpu"},
        {"q": "What does URL stand for?", "a": "uniform resource locator"},
        {"q": "What is the most popular search engine?", "a": "google"},
        {"q": "Which data structure uses LIFO?", "a": "stack"},
        {"q": "Which data structure uses FIFO?", "a": "queue"},
        {"q": "What does GUI stand for?", "a": "graphical user interface"},
        {"q": "What is the extension for a Python file?", "a": ".py"},
        {"q": "Who is the CEO of Tesla and owner of X?", "a": "elon musk"},
        {"q": "What is the smallest unit of data in a computer?", "a": "bit"},
        {"q": "How many bits are in a byte?", "a": "8"},
        {"q": "Which protocol is used for sending emails?", "a": "smtp"},
        {"q": "What does IP stand for in networking?", "a": "internet protocol"},
        {"q": "Which language is primarily used for Android apps?", "a": "kotlin"},
        {"q": "What is the primary function of a router?", "a": "forward data"},
        {"q": "What does SSD stand for?", "a": "solid state drive"},
        {"q": "Who created the World Wide Web?", "a": "tim berners-lee"}
    ],
    "english": [
        {"q": "What is the plural of 'child'?", "a": "children"},
        {"q": "Who wrote 'Romeo and Juliet'?", "a": "william shakespeare"},
        {"q": "What is a word that means the opposite of 'happy'?", "a": "sad"},
        {"q": "What is the past tense of 'run'?", "a": "ran"},
        {"q": "Which part of speech describes a noun?", "a": "adjective"},
        {"q": "What is a person, place, or thing called?", "a": "noun"},
        {"q": "How many vowels are in the English alphabet?", "a": "5"},
        {"q": "What is the largest word in English?", "a": "pneumonoultramicroscopicsilicovolcanoconiosis"},
        {"q": "What punctuation ends a question?", "a": "?"},
        {"q": "Who wrote 'Harry Potter'?", "a": "j.k. rowling"},
        {"q": "What is a synonym for 'large'?", "a": "big"},
        {"q": "Which word is a pronoun?", "a": "he"},
        {"q": "What is the comparative form of 'good'?", "a": "better"},
        {"q": "What is the superlative form of 'bad'?", "a": "worst"},
        {"q": "What is the main character in a story called?", "a": "protagonist"},
        {"q": "What is the opposing character in a story called?", "a": "antagonist"},
        {"q": "What type of word is 'quickly'?", "a": "adverb"},
        {"q": "What is the first letter of the alphabet?", "a": "a"},
        {"q": "What prefix means 'again'?", "a": "re"},
        {"q": "What suffix means 'without'?", "a": "less"},
        {"q": "Who wrote 'The Great Gatsby'?", "a": "f. scott fitzgerald"},
        {"q": "What is a poem with 14 lines called?", "a": "sonnet"},
        {"q": "Which play features a character named Hamlet?", "a": "hamlet"},
        {"q": "What is the study of word origins called?", "a": "etymology"},
        {"q": "What is a collection of letters called?", "a": "alphabet"},
        {"q": "What is the past participle of 'go'?", "a": "gone"},
        {"q": "What is a figure of speech comparing two things using 'like'?", "a": "simile"},
        {"q": "What is a figure of speech comparing two things directly?", "a": "metaphor"},
        {"q": "What is the plural of 'sheep'?", "a": "sheep"},
        {"q": "What is the smallest unit of a story?", "a": "sentence"}
    ]
}
